# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://praveenprakash9441:praveen123@cluster0.mpp7j.mongodb.net/PGmadeEazy?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=PGmadeEazy
spring.data.mongodb.auto-index-creation=true

# Server Configuration
server.port=${PORT:8080}

# JWT Configuration
jwt.secret=${JWT_SECRET:Yv3gT8nqLpB9mX2aF7sD4wZ0vJhCr6Qe}
# 1 day in milliseconds
jwt.expiration=86400000

# Spring Security Configuration
spring.security.user.name=${SECURITY_USER_NAME:admin}
spring.security.user.password=${SECURITY_USER_PASSWORD:admin}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dc04mbt7x}
cloudinary.api-key=${CLOUDINARY_API_KEY:292559389546916}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:u4Pc1gJJ_Ew4XFMlSNrxo3QhqA4}
cloudinary.folder=pgmadeeazy
cloudinary.max-size=10485760
cloudinary.allowed-types=image/jpeg,image/png,image/webp

# CORS Configuration
cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

# Property Configuration
property.location.radius=5000
property.maxImages=5

# PayPal Configuration
paypal.client.id=AeUZfiOiCnkMD9yws8LPCDPAHTH2U1Lg0BIZPVDZofCKkjSi1Av805VMzC8QGw3r2LYfXhYoK4tURZCo
paypal.client.secret=EIAsQipLcF6_72n5wR6YUi0kLuFVAgboxMPcitD92X59-zAF81WaXVl3Tj6WA0XIrem1p1LOwaDzWTdQ
paypal.mode=sandbox
paypal.base.url=https://api-m.sandbox.paypal.com

# Logging Configuration
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
logging.level.com.pgmadeeazy=DEBUG
logging.level.com.cloudinary=DEBUG
logging.level.com.sun.mail=DEBUG
logging.level.org.springframework.web=DEBUG

# Spring Boot Configuration
spring.main.allow-bean-definition-overriding=true

# Multipart configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=${java.io.tmpdir}

# File upload directory
file.upload-dir=./uploads

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pgmadeeazy@gmail.com
spring.mail.password=uratrtetjnjircqj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Enable async processing for email sending
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25
